package speedmentpojo.localhost.db0.web1.user.impl;

import com.speedment.Speedment;
import com.speedment.internal.core.code.AbstractBaseEntity;
import java.util.Objects;
import java.util.Optional;
import java.util.StringJoiner;
import javax.annotation.Generated;
import speedmentpojo.localhost.db0.web1.user.User;

/**
 * An implementation representing an entity (for example, a row) in the Table
 * 'localhost.db0.web1.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public final class UserImpl extends AbstractBaseEntity<User> implements User {
    
    private Integer id;
    private String name;
    private String password;
    
    UserImpl(Speedment speedment) {
        super(speedment);
    }
    
    public UserImpl(Speedment speedment, final User user) {
        super(speedment);
        setId(user.getId());
        user.getName().ifPresent(this::setName);
        user.getPassword().ifPresent(this::setPassword);
    }
    
    @Override
    public Integer getId() {
        return id;
    }
    
    @Override
    public Optional<String> getName() {
        return Optional.ofNullable(name);
    }
    
    @Override
    public Optional<String> getPassword() {
        return Optional.ofNullable(password);
    }
    
    @Override
    public final UserImpl setId(Integer id) {
        this.id = id;
        return this;
    }
    
    @Override
    public final UserImpl setName(String name) {
        this.name = name;
        return this;
    }
    
    @Override
    public final UserImpl setPassword(String password) {
        this.password = password;
        return this;
    }
    
    @Override
    public User copy() {
        return new UserImpl(getSpeedment_(), this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("name = "+Objects.toString(getName().orElse(null)));
        sj.add("password = "+Objects.toString(getPassword().orElse(null)));
        return "UserImpl "+sj.toString();
    }
    
    @Override
    public boolean equals(Object that) {
        if (this == that) { return true; }
        if (!(that instanceof User)) { return false; }
        @SuppressWarnings("unchecked")
        final User thatUser = (User)that;
        if (!Objects.equals(this.getId(), thatUser.getId())) {return false; }
        if (!Objects.equals(this.getName(), thatUser.getName())) {return false; }
        if (!Objects.equals(this.getPassword(), thatUser.getPassword())) {return false; }
        return true;
    }
    
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(getId());
        hash = 31 * hash + Objects.hashCode(getName());
        hash = 31 * hash + Objects.hashCode(getPassword());
        return hash;
    }
    
    @Override
    public Class<User> getEntityClass_() {
        return User.class;
    }
}