package speedmentpojo.localhost.db0.web1.user;

import com.speedment.Entity;
import com.speedment.field.ComparableField;
import com.speedment.field.StringField;
import com.speedment.internal.core.field.ComparableFieldImpl;
import com.speedment.internal.core.field.StringFieldImpl;
import java.util.Optional;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table
 * 'localhost.db0.web1.user'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public interface User extends Entity<User> {
    
    /**
     * This Field corresponds to the {@link User} field that can be obtained
     * using the {@link User#getId()} method.
     */
    public final static ComparableField<User, Integer> ID = new ComparableFieldImpl<>("id", User::getId, User::setId);
    /**
     * This Field corresponds to the {@link User} field that can be obtained
     * using the {@link User#getName()} method.
     */
    public final static StringField<User> NAME = new StringFieldImpl<>("name", o -> o.getName().orElse(null), User::setName);
    /**
     * This Field corresponds to the {@link User} field that can be obtained
     * using the {@link User#getPassword()} method.
     */
    public final static StringField<User> PASSWORD = new StringFieldImpl<>("password", o -> o.getPassword().orElse(null), User::setPassword);
    
    /**
     * Returns the id of this User. The id field corresponds to the database
     * column db0.web1.user.id.
     * 
     * @return the id of this User
     */
    Integer getId();
    
    /**
     * Returns the name of this User. The name field corresponds to the database
     * column db0.web1.user.name.
     * 
     * @return the name of this User
     */
    Optional<String> getName();
    
    /**
     * Returns the password of this User. The password field corresponds to the
     * database column db0.web1.user.password.
     * 
     * @return the password of this User
     */
    Optional<String> getPassword();
    
    /**
     * Sets the id of this User. The id field corresponds to the database column
     * db0.web1.user.id.
     * 
     * @param id to set of this User
     * @return this User instance
     */
    User setId(Integer id);
    
    /**
     * Sets the name of this User. The name field corresponds to the database
     * column db0.web1.user.name.
     * 
     * @param name to set of this User
     * @return this User instance
     */
    User setName(String name);
    
    /**
     * Sets the password of this User. The password field corresponds to the
     * database column db0.web1.user.password.
     * 
     * @param password to set of this User
     * @return this User instance
     */
    User setPassword(String password);
}