package speedmentpojo.localhost.db0.web1.test.impl;

import com.speedment.Speedment;
import com.speedment.config.Column;
import com.speedment.config.Table;
import com.speedment.config.mapper.TypeMapper;
import com.speedment.exception.SpeedmentException;
import com.speedment.internal.core.config.mapper.identity.IntegerIdentityMapper;
import com.speedment.internal.core.config.mapper.identity.StringIdentityMapper;
import com.speedment.internal.core.manager.sql.AbstractSqlManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.annotation.Generated;
import speedmentpojo.localhost.db0.web1.test.Test;

/**
 * A manager implementation representing an entity (for example, a row) in
 * the Table 'localhost.db0.web1.test'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class TestManagerImpl extends AbstractSqlManager<Test> {
    
    private final TypeMapper<Integer, Integer> idTypeMapper = new IntegerIdentityMapper();
    private final TypeMapper<String, String> sexTypeMapper = new StringIdentityMapper();
    
    public TestManagerImpl(Speedment speedment) {
        super(speedment);
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public Class<Test> getEntityClass() {
        return Test.class;
    }
    
    @Override
    public Object get(Test entity, Column column) {
        switch (column.getName()) {
            case "id" : return entity.getId();
            case "sex" : return entity.getSex();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    public void set(Test entity, Column column, Object value) {
        switch (column.getName()) {
            case "id" : entity.setId((Integer) value); break;
            case "sex" : entity.setSex((String) value); break;
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    public Table getTable() {
        return speedment.getProjectComponent().getProject().findTableByName("db0.web1.test");
    }
    
    protected Test defaultReadEntity(ResultSet resultSet) {
        final Test entity = newInstance();
        try {
            entity.setId(idTypeMapper.toJavaType(resultSet.getInt(1)));
            entity.setSex(sexTypeMapper.toJavaType(resultSet.getString(2)));
        }
        catch (SQLException sqle) {
            throw new SpeedmentException(sqle);
        }
        return entity;
    }
    
    @Override
    public Test newInstance() {
        return new TestImpl(speedment);
    }
    
    @Override
    public Integer primaryKeyFor(Test entity) {
        return entity.getId();
    }
}